### ISSUE TITLE
실시간 객체탐지 대상 결정 및 시나리오 구상

### ISSUE THREAD

**Issue by Maeng89** [SESAC-AIoT/maeng#13]
yolo base

**Comment by smg8824project** [comment]
1. 객체탐지모델
 - yolov3
2. 객체탐지대상
 - 사람, 개, 고양이
3. 활용서비스 
 -

**Comment by Maeng89** [comment]
[고양이가 먹으면 안되는 식물](https://mypetlife.co.kr/premium/%EA%B3%A0%EC%96%91%EC%9D%B4%EC%97%90%EA%B2%8C-%EC%9C%84%ED%97%98%ED%95%9C-%EC%8B%9D%EB%AC%BC-%EC%95%88%EC%A0%84%ED%95%9C-%EC%8B%9D%EB%AC%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0/)

**Comment by Maeng89** [comment]
1. 반려묘 접근 알림 가정용 스마트팜(식물 종류 무관 - 화분)
- 얼갈이 분류 모델, 고양이/화분 객체탐지(로깅, 알림, 거리 측정-후순위)

2. 캣그라스 스마트팜(캣그라스 전용)     -> 아이덴티티가 구체적이므로 확정 
- 캣그라스 분류 모델, 고양이/화분 객체 탐지(로깅, 알림, 거리 측정-가능시)
- 데이터셋 고민
