### ISSUE TITLE
젯슨나노 셋팅

### ISSUE THREAD

**Issue by Maeng89** [SESAC-AIoT/maeng#5]
< 노션 및 구글드라이브 aiot 강의 자료 참고 >

network : wifi 내부망 Nugunaaiot1_ASUS / 비번 동일
OS : 우분투 18.04
OS 및 VNC 공통 비번 : yahboom
VNC : 젯슨나노 기본 해상도가 매우 높아서 원격 연결 최적화를 위해 tightVNC 사용
VNC server ip adress : 192.168.50.90
원격 연결 성능 최적화를 위해 해상도를 1024*768로 변경

**Comment by Maeng89** [comment]
- sudo apt-get update 및 upgrade 완료
- csi camer 설치 및 실행 확인 완료

**Comment by smg8824project** [comment]
![Image](https://user-images.githubusercontent.com/117341985/219294449-5d2a6344-ec1d-4723-8c82-603f02d78d2d.png)
